version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: matchduo_db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PW}
      MYSQL_DATABASE: matchduo_db
    ports:
      - "3306:3306"
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--requirepass", "${REDIS_PW}"]
    container_name: matchduo_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  app_blue:
    image: ${APP_IMAGE}
    container_name: matchduo_app_blue
    networks:
      - app_net
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
    volumes:
      - /home/ubuntu/application-secret.yml:/app/application-secret.yml
    restart: always

  app_green:
    image: ${APP_IMAGE}
    container_name: matchduo_app_green
    networks:
      - app_net
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
    volumes:
      - /home/ubuntu/application-secret.yml:/app/application-secret.yml
    restart: always

networks:
  app_net:
    name: web7_9_finalscreening_be_default
    external: true

volumes:
  mysql_data:
  redis_data:
