DB_HOST: localhost
DB_PORT: 3306
DB_NAME: matchduo_db
DB_USER: root
DB_PASSWORD: password123!

# Riot API 설정
RIOT_API_KEY: RGAPI-8e0c8bf4-1ca0-46e6-9bea-aa764831e195
RIOT_API_BASE_URL: https://asia.api.riotgames.com